## Continue numpy 

In [1]:
import numpy as np

In [4]:
np.random.rand(3,2)

array([[0.91607396, 0.15808604],
       [0.67413149, 0.80189543],
       [0.86110391, 0.12344328]])

In [7]:
np.random.randn(3,2)

array([[ 0.5911767 ,  1.34979601],
       [ 1.14512279, -0.27360819],
       [-1.70700942,  1.17681091]])

In [9]:
np.random.randint(34,100)

38

In [10]:
np.random.randint(20,56,100)

array([49, 24, 37, 20, 46, 25, 20, 30, 37, 23, 28, 52, 45, 46, 26, 33, 26,
       52, 38, 48, 42, 36, 31, 33, 26, 42, 43, 34, 47, 48, 28, 39, 32, 35,
       44, 23, 48, 45, 28, 30, 55, 43, 25, 40, 42, 25, 34, 50, 47, 40, 52,
       44, 31, 40, 38, 20, 49, 42, 44, 25, 28, 51, 55, 41, 30, 38, 23, 26,
       46, 24, 50, 53, 52, 25, 48, 51, 32, 42, 55, 22, 24, 50, 35, 24, 29,
       22, 24, 25, 40, 53, 22, 34, 43, 45, 24, 38, 50, 42, 45, 29])

In [12]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
rand_array=np.random.randint(0,100,20)
rand_array

array([62, 83, 74, 49, 83, 59, 95, 95, 65, 72, 91, 96, 48, 43, 47,  4, 94,
        4, 41,  9])

In [14]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:
sample_array.reshape(3,7)

ValueError: cannot reshape array of size 30 into shape (3,7)

In [16]:
rand_array.min()

4

In [32]:
rand_array.argmin()

15

In [17]:
sample_array.dtype

dtype('int32')

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
a=np.random.rand(2,3)
a

array([[0.98165575, 0.14659761, 0.59398864],
       [0.91026213, 0.37055651, 0.50065161]])

In [21]:
a.T

array([[0.98165575, 0.91026213],
       [0.14659761, 0.37055651],
       [0.59398864, 0.50065161]])

In [23]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
sample_array[3]

13

In [25]:
sample_array[3:7]

array([13, 14, 15, 16])

In [26]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [28]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [30]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [31]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [36]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

## Two Dimensional Array

In [37]:
import numpy as np

In [38]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [39]:
sample_matrix[0][2]

1

In [40]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

In [42]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

## Selection techniques

In [43]:
test_array=np.arange(5,25)
test_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [44]:
test_array+test_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [45]:
np.exp(test_array) #exponential

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10])

In [46]:
np.sqrt(test_array)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [47]:
np.log(test_array)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [48]:
np.max(test_array)

24

In [49]:
np.min(test_array)

5

In [50]:
np.argmax(test_array)

19

In [51]:
np.argmin(test_array)

0

In [52]:
np.square(test_array)

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289,
       324, 361, 400, 441, 484, 529, 576], dtype=int32)

In [53]:
np.std(test_array)

5.766281297335398

In [54]:
np.var(test_array)

33.25

In [55]:
np.mean(test_array)

14.5

In [57]:
array=np.random.randn(3,4)
array

array([[-0.95738971,  0.56647878,  0.75443846, -2.39064874],
       [-1.69368073,  1.00446625,  0.36048378,  1.72708101],
       [ 0.17658489,  0.59713713,  0.9248938 , -0.06789833]])

In [58]:
np.round(array,decimals=4)

array([[-0.9574,  0.5665,  0.7544, -2.3906],
       [-1.6937,  1.0045,  0.3605,  1.7271],
       [ 0.1766,  0.5971,  0.9249, -0.0679]])

In [59]:
sports=np.array(['golf','cricket','fball','cricket','football'])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')

### Pandas-> To create data,create table,manipulation

In [61]:
import pandas as pd
import numpy as np

In [67]:
tables=['a','b','c','d']
test_list=[1000,2000,3000,4000]
arrays=np.array([11,12,13,14])
dict={'a':1,'b':2,'c':3,'d':4}

In [68]:
pd.Series(data=test_list)

0    1000
1    2000
2    3000
3    4000
dtype: int64

In [74]:
pd.Series(data=test_list,index=tables)

a    1000
b    2000
c    3000
d    4000
dtype: int64

In [78]:
pd.Series(test_list,tables)

a    1000
b    2000
c    3000
d    4000
dtype: int64

In [77]:
pd.Series(dict)

a    1
b    2
c    3
d    4
dtype: int64

## Panda
### panda dataframe and indexing

In [80]:
sp1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sp1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [81]:
sp1['cricket']

1

In [82]:
sp2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sp2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [83]:
sp1+sp2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [84]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='sc1 sc2 sc3 sc4 sc5'.split())

In [85]:
df1

sc1       sc2       sc3       sc4       sc5
A  0.880617  0.832545  0.776039  0.763327  0.314471
B  0.626881  0.144367  0.260142  0.311059  0.941592
C  0.750366  0.028077  0.580110  0.403588  0.842810
D  0.616194  0.672777  0.030276  0.596309  0.563026
E  0.772971  0.024121  0.011603  0.321619  0.959055
F  0.147738  0.435503  0.025496  0.915760  0.543805
G  0.047716  0.089459  0.932306  0.077662  0.479533
H  0.616694  0.072049  0.486076  0.810896  0.098825

In [87]:
df1['sc3']

A    0.776039
B    0.260142
C    0.580110
D    0.030276
E    0.011603
F    0.025496
G    0.932306
H    0.486076
Name: sc3, dtype: float64

In [93]:
df1[['sc1','sc2','sc3']]

sc1       sc2       sc3
A  0.880617  0.832545  0.776039
B  0.626881  0.144367  0.260142
C  0.750366  0.028077  0.580110
D  0.616194  0.672777  0.030276
E  0.772971  0.024121  0.011603
F  0.147738  0.435503  0.025496
G  0.047716  0.089459  0.932306
H  0.616694  0.072049  0.486076

In [92]:
df1['sc6']=df1['sc1']+df1['sc2']
df1

sc1       sc2       sc3       sc4       sc5       sc6
A  0.880617  0.832545  0.776039  0.763327  0.314471  1.713162
B  0.626881  0.144367  0.260142  0.311059  0.941592  0.771248
C  0.750366  0.028077  0.580110  0.403588  0.842810  0.778443
D  0.616194  0.672777  0.030276  0.596309  0.563026  1.288970
E  0.772971  0.024121  0.011603  0.321619  0.959055  0.797093
F  0.147738  0.435503  0.025496  0.915760  0.543805  0.583241
G  0.047716  0.089459  0.932306  0.077662  0.479533  0.137174
H  0.616694  0.072049  0.486076  0.810896  0.098825  0.688743

In [96]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [97]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [98]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [99]:
df.drop("ID",axis=1)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [100]:
df.drop(3)

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
4  176  Lally     123

### How to import Dataset using Pandas?

In [101]:
import numpy as np
import pandas as pd

In [102]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Financial-Analytics-Loan-Approval-Prediction/main/loan_prediction.csv")

In [103]:
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [109]:
df.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [111]:
df.sample(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
437  LP002401   Male     Yes          0      Graduate            No   
344  LP002128   Male     Yes          2      Graduate           NaN   
135  LP001488   Male     Yes         3+      Graduate            No   
235  LP001784   Male     Yes          1      Graduate            No   
62   LP001207   Male     Yes          0  Not Graduate           Yes   
57   LP001197   Male     Yes          0      Graduate            No   
60   LP001205   Male     Yes          0      Graduate            No   
207  LP001698   Male      No          0  Not Graduate            No   
576  LP002872    NaN     Yes          0      Graduate            No   
252  LP001841   Male      No          0  Not Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
437             2213             1125.0         NaN             360.0   
344             2583             2330.0       125.0             360.0   
135             4000             7750.0       290.0             360.0   
235             5500             1260.0       170.0             360.0   
62              2609             3449.0       165.0             180.0   
57              3366             2200.0       135.0             360.0   
60              2500             3796.0       120.0             360.0   
207             3975             2531.0        55.0             360.0   
576             3087             2210.0       136.0             360.0   
252             2583             2167.0       104.0             360.0   

     Credit_History Property_Area Loan_Status  
437             1.0         Urban           Y  
344             1.0         Rural           Y  
135             1.0     Semiurban           N  
235             1.0         Rural           Y  
62              0.0         Rural           N  
57              1.0         Rural           N  
60              1.0         Urban           Y  
207             1.0         Rural           Y  
576             0.0     Semiurban           N  
252             1.0         Rural           Y

In [105]:
df.shape

(614, 13)

In [106]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [108]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [113]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [114]:
df.describe(include="all")

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN