## Data Structures

## Lists 
### list elements are separated by comma and enclosed within square brackets. 
### lists are mutable
### list-> hetrogeneouse
### list can be retrieved using index

In [1]:
sample_list=[1,13.6,"hi",True,12,1]
sample_list

[1, 13.6, 'hi', True, 12, 1]

In [2]:
sample_list[2]

'hi'

In [3]:
sample_list[10]

IndexError: list index out of range

In [6]:
sample_list[-1]

1

In [7]:
sample_list[-2]

12

In [8]:
sample_list[0]=100

In [9]:
sample_list

[100, 13.6, 'hi', True, 12, 1]

## Tuple

### hetrogenouse 

### paranthesis

### can retirieve data using index

### immutable



In [13]:
sample_tuple=(1,13,6,"hi",12,1)
sample_tuple

(1, 13, 6, 'hi', 12, 1)

In [14]:
sample_tuple[0]

1

In [15]:
sample_tuple[24]

IndexError: tuple index out of range

In [16]:
sample_tuple[0]=100

TypeError: 'tuple' object does not support item assignment

## Set
### doesnot allow duplicates 
### elements cannot be retrieved using index
### set is mutable but not using indexes

In [19]:
sample_set={1,13.6,"hi",12,1,127,25,25,"apple","king","ball"}
sample_set

{1, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [20]:
sample_set[0]

TypeError: 'set' object is not subscriptable

In [21]:
sample_set[0]="hello"

TypeError: 'set' object does not support item assignment

In [23]:
sample_set.add(1000)

In [24]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [25]:
sample_set.remove("hi")

In [26]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'king'}

## Dictionary
### dict comes as key- value pair DS
### values can be duplicated
### Value can be retrieved using key
### key cannot be retrieved using index/value

In [29]:
sample_dict={1:"apple",2:35.4,3:"data",2:"every",6:"35.4",7:35.4}
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 35.4}

In [30]:
sample_dict[3]

'data'

In [31]:
sample_dict[4]

KeyError: 4

In [32]:
sample_dict[7]

35.4

In [33]:
sample_dict[apple]

NameError: name 'apple' is not defined

In [34]:
sample_dict[7]=100

In [35]:
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 100}

In [36]:
sample_dict[10]="business"

In [37]:
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 100, 10: 'business'}

## Numpy:Package for Multidimentsional array 

In [ ]:
## np is the alias of the numpy

In [38]:
import numpy as np

In [39]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [52]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [50]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [56]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
#### create an array of zeros with 2 rows and 10 columns

In [59]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [62]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [63]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
np.random.rand(3,2)

array([[0.88549186, 0.04262158],
       [0.84403542, 0.00511549],
       [0.4302041 , 0.12053814]])

In [65]:
np.random.randn(3,2)

array([[-0.58949676, -0.26356007],
       [ 0.93655641,  0.21497777],
       [ 0.9633804 , -0.18904265]])

In [66]:
np.random.randint(34,100)

62

In [67]:
np.random.randint(20,56,100)

array([54, 29, 26, 29, 54, 48, 41, 39, 28, 29, 50, 47, 20, 31, 33, 29, 41,
       55, 46, 45, 31, 46, 27, 27, 30, 51, 39, 45, 27, 24, 35, 53, 36, 38,
       36, 50, 34, 31, 50, 27, 20, 35, 44, 31, 49, 43, 48, 24, 47, 53, 39,
       39, 41, 30, 20, 51, 53, 23, 46, 24, 21, 49, 44, 36, 35, 38, 55, 25,
       44, 44, 36, 29, 37, 39, 45, 49, 42, 44, 37, 20, 51, 42, 22, 43, 43,
       30, 39, 46, 30, 37, 33, 27, 48, 41, 42, 36, 41, 23, 36, 44])